name: CD

on: 
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Bundle
      run: mkdir ./out && mkdir ./out/wordpress-promo && cp -r css fonts img icons ./out/wordpress-promo/ && cp index.html ./out/wordpress-promo/
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: MemboLembo/MemboLembo.github.io
        publish_dir: ./out
        publish_branch: master
